import numpy as np
import matplotlib.pyplot as plt
import logging
from .mathematics import math as matmath
import struct
import requests
from bs4 import BeautifulSoup
import json
import base64
import time
import re

class tools:
    @staticmethod
    def fetch(url):
        """
        Scrape text content from a URL for model training.
        """
        try:
            response = requests.get(url, timeout=10)
            response.raise_for_status()
                
            soup = BeautifulSoup(response.text, 'html.parser')

            for script in soup(["script", "style"]):
                script.decompose()
            text = soup.get_text()
            lines = (line.strip() for line in text.splitlines())
            chunks = (phrase.strip() for line in lines for phrase in line.split("  "))
            clean_text = ' '.join(chunk for chunk in chunks if chunk)
                
            return clean_text
        except Exception as e:
                return f"Error: {str(e)}"
            
    @staticmethod
    def imagegen(prompt, negative_prompt="", api_url="http://127.0.0.1:7860", steps=20, cfg_scale=7.0, width=512, height=512):
        """
        Bridge to a local Stable Diffusion API (e.g., Automatic1111).
        This sends the prompt to the API, decodes the response, and saves the image.
            
        Args:
            prompt (str): The visual description generated by the AI or user.
            api_url (str): The address where the image generation API is listening.
            
        Returns:
            str: The filename of the saved image, or an error message.
        """
        print(f"Connecting to Local Image API at {api_url}...")

        payload = {
            "prompt": prompt,
            "negative_prompt": negative_prompt,
            "steps": steps,
            "cfg_scale": cfg_scale,
            "width": width,
            "height": height,
            "sampler_name": "Euler a", 
            }

        try:
            endpoint = f"{api_url}/sdapi/v1/txt2img"

            response = requests.post(endpoint, json=payload, timeout=180) 
            response.raise_for_status()

            r = response.json()
            base64_image = r['images'][0]

            cleaned_prompt = re.sub(r'[^a-zA-Z0-9]', '', prompt[:30])
            timestamp = int(time.time())
            filename = f"generated_img_{cleaned_prompt}_{timestamp}.png"
                
            with open(filename, 'wb') as f:
                f.write(base64.b64decode(base64_image.split(",",1)[0])) 
                    
            print(f"Image successfully generated and saved to: {filename}")
            return filename

        except ConnectionRefusedError:
            error_msg = f"Error: Could not connect to the image generation server. Please ensure that a local Stable Diffusion API (e.g., Automatic1111 running at {api_url} with --api enabled) is running."
            print(error_msg)
            return error_msg
        except Exception as e:
            error_msg = f"An unexpected error occurred during image generation: {str(e)}"
            print(error_msg)
            return error_msg
